In [1]:
import pandas as pd
import numpy as np

df_00_v_todo_event_raw_clean_data = pd.read_parquet("output_aggregate_data\\00_v_todo_event_raw_clean.parquet")
df_00_v_todo_event_raw_clean_data.head()

,event_id,user_id,session_id,event_time,event_date,event_type,task_id,list_id,device_type,os,...,has_reminder,task_status,action_duration,attr_new_priority,attr_new_due_date,attr_query,attr_result_count,attr_feature_name,attr_close_reason,attributes
0,log_0000103101,user_006111,user_006111_sess_0001,2026-07-01 00:00:06,2026-07-01,create_task,task_00103101,list_user_006111_02,desktop,windows,...,False,deleted,45,None,None,None,NaN,None,None,"{""priority"": ""medium"", ""due_date"": ""2026-07-01..."
1,log_0000143029,user_000861,user_000861_sess_0001,2026-07-01 00:00:57,2026-07-01,create_task,task_00143029,list_user_000861_02,mobile,android,...,False,completed,67,None,None,None,NaN,None,None,"{""priority"": ""medium"", ""due_date"": null, ""has_..."
2,log_0000050094,user_001083,user_001083_sess_0001,2026-07-01 00:01:30,2026-07-01,create_task,task_00050094,list_user_001083_03,tablet,ios,...,False,active,91,None,None,None,NaN,None,None,"{""priority"": ""medium"", ""due_date"": null, ""has_..."
3,log_0000094231,user_008703,user_008703_sess_0001,2026-07-01 00:01:33,2026-07-01,create_task,task_00094231,list_user_008703_01,mobile,ios,...,True,completed,57,None,None,None,NaN,None,None,"{""priority"": ""high"", ""due_date"": ""2026-07-23"",..."
4,log_0000064257,user_009605,user_009605_sess_0001,2026-07-01 00:02:02,2026-07-01,create_task,task_00064257,list_user_009605_02,mobile,ios,...,False,active,82,None,None,None,NaN,None,None,"{""priority"": ""low"", ""due_date"": null, ""has_rem..."

In [2]:
df_00_v_todo_event_raw_clean_data.columns

Index(['event_id', 'user_id', 'session_id', 'event_time', 'event_date',
       'event_type', 'task_id', 'list_id', 'device_type', 'os', 'app_version',
       'network_type', 'province', 'city', 'user_level', 'user_type', 'gender',
       'age_group', 'is_active', 'register_channel', 'task_priority',
       'due_date', 'task_create_time', 'task_complete_time',
       'task_is_completed', 'has_subtask', 'has_reminder', 'task_status',
       'action_duration', 'attr_new_priority', 'attr_new_due_date',
       'attr_query', 'attr_result_count', 'attr_feature_name',
       'attr_close_reason', 'attributes'],
      dtype='object')

In [3]:
df_01_dwd_todo_event_detail_data = pd.read_parquet("output_aggregate_data\\01_dwd_todo_event_detail.parquet")
df_01_dwd_todo_event_detail_data.head()

,event_id,user_id,task_id,list_id,event_type,event_time,event_date,session_id,device_type,os,...,has_reminder,task_status,action_duration,attr_new_priority,attr_new_due_date,attr_query,attr_result_count,attr_feature_name,attr_close_reason,attributes
0,log_0000103101,user_006111,task_00103101,list_user_006111_02,create_task,2026-07-01 00:00:06,2026-07-01,user_006111_sess_0001,desktop,windows,...,False,deleted,45,None,None,None,NaN,None,None,"{""priority"": ""medium"", ""due_date"": ""2026-07-01..."
1,log_0000143029,user_000861,task_00143029,list_user_000861_02,create_task,2026-07-01 00:00:57,2026-07-01,user_000861_sess_0001,mobile,android,...,False,completed,67,None,None,None,NaN,None,None,"{""priority"": ""medium"", ""due_date"": null, ""has_..."
2,log_0000050094,user_001083,task_00050094,list_user_001083_03,create_task,2026-07-01 00:01:30,2026-07-01,user_001083_sess_0001,tablet,ios,...,False,active,91,None,None,None,NaN,None,None,"{""priority"": ""medium"", ""due_date"": null, ""has_..."
3,log_0000094231,user_008703,task_00094231,list_user_008703_01,create_task,2026-07-01 00:01:33,2026-07-01,user_008703_sess_0001,mobile,ios,...,True,completed,57,None,None,None,NaN,None,None,"{""priority"": ""high"", ""due_date"": ""2026-07-23"",..."
4,log_0000064257,user_009605,task_00064257,list_user_009605_02,create_task,2026-07-01 00:02:02,2026-07-01,user_009605_sess_0001,mobile,ios,...,False,active,82,None,None,None,NaN,None,None,"{""priority"": ""low"", ""due_date"": null, ""has_rem..."

In [4]:
df_01_dwd_todo_event_detail_data.columns

Index(['event_id', 'user_id', 'task_id', 'list_id', 'event_type', 'event_time',
       'event_date', 'session_id', 'device_type', 'os', 'app_version',
       'network_type', 'province', 'city', 'user_level', 'user_type', 'gender',
       'age_group', 'is_active', 'register_channel', 'task_priority',
       'due_date', 'task_create_time', 'task_complete_time',
       'task_is_completed', 'has_subtask', 'has_reminder', 'task_status',
       'action_duration', 'attr_new_priority', 'attr_new_due_date',
       'attr_query', 'attr_result_count', 'attr_feature_name',
       'attr_close_reason', 'attributes'],
      dtype='object')

In [5]:
df_02_dwd_task_lifecycle_data = pd.read_parquet("output_aggregate_data\\02_dwd_task_lifecycle.parquet")
df_02_dwd_task_lifecycle_data.head()

,task_id,user_id,create_time,first_complete_time,last_update_time,complete_duration_seconds,is_completed,is_overdue,priority,has_reminder,has_subtask,task_status,due_date
0,task_00030645,user_004644,2026-07-01 00:32:06,NaT,2026-07-01 00:32:06,NaN,False,False,low,False,False,active,2026-07-31
1,task_00161905,user_001913,2026-07-01 00:39:20,2026-08-08 09:12:46,2026-08-08 09:12:46,3314006.0,True,True,high,True,False,completed,2026-07-06
2,task_00143935,user_008452,2026-07-01 00:40:00,2026-07-24 22:47:27,2026-07-24 22:47:27,2066847.0,True,False,low,True,False,completed,2026-07-30
3,task_00144427,user_002549,2026-07-01 01:15:02,NaT,2026-07-01 01:15:02,NaN,False,False,low,False,True,active,2026-07-07
4,task_00112044,user_002782,2026-07-01 01:21:41,2026-07-11 13:19:12,2026-07-11 13:19:12,907051.0,True,False,low,True,False,completed,2026-07-14

In [6]:
df_02_dwd_task_lifecycle_data.columns

Index(['task_id', 'user_id', 'create_time', 'first_complete_time',
       'last_update_time', 'complete_duration_seconds', 'is_completed',
       'is_overdue', 'priority', 'has_reminder', 'has_subtask', 'task_status',
       'due_date'],
      dtype='object')

In [7]:
df_03_dwd_user_active_detail_data = pd.read_parquet("output_aggregate_data\\03_dwd_user_active_detail.parquet")
df_03_dwd_user_active_detail_data.head()

,user_id,active_date,first_event_time,last_event_time,event_cnt,session_cnt
0,user_000001,2026-07-04,2026-07-04 09:33:39,2026-07-04 09:33:39,1,1
1,user_000001,2026-07-06,2026-07-06 05:17:02,2026-07-06 18:30:45,3,3
2,user_000001,2026-07-10,2026-07-10 08:40:27,2026-07-10 08:40:27,1,1
3,user_000001,2026-07-11,2026-07-11 18:19:08,2026-07-11 18:19:08,1,1
4,user_000001,2026-07-16,2026-07-16 21:49:14,2026-07-16 21:49:14,1,1

In [ ]:
df_03_dwd_user_active_detail_data.columns

Index(['user_id', 'active_date', 'first_event_time', 'last_event_time',
       'event_cnt', 'session_cnt'],
      dtype='object')